### ISSUE TITLE
[Feature request] Supporting substitutions in string parameters

### ISSUE THREAD

**Issue by mgrojo** [rocher/mold_lib#14]
Hi @rocher,

Very interesting project.

After a quick look, I think the library doesn't support substituting inside a passed string. I have a project idea in which the program will programmatically determine the values to make the substitution in a template. The template could be passed to the program by the user, but I'd like also to have a default template valid for most use cases. If the default template could be stored in memory as a string, there wouldn't be any need to add it to the program as a resource (either external or embedded with some library). The program determines the values, it calls mold_lib to do the substitutions passing the default in memory template, and the resulting string is dumped to the final file by the program.

**Comment by rocher** [comment]
Hi @mgrojo,

Thanks for the suggestion!!  As you can see, mold_lib has only one single call that operates on external files (input template, input variables -toml file- and output directory). This is, in my opinion, the most common use case for these kind of tools. Right now the input template can be a single file or a directory, and of course there is no problem having it in memory.

The use use case you propose is easy to implement, even with some variants. For example, instead of an external file of variable definitions, you could directly provide a map from unbounded string to unbounded string to provide the required variable -->  value mapping. If you want to work only in memory, wouldn't that be more appropriate? Also, what about using environment variables?
The same with the output: the function could return an unbounded_string or dump the result to a file. And regarding the output file, it could be possible to provide just a string filename or, if an already opened text stream is passed, append the result string in that text stream.

Let me think how can I slightly refactor the implementation to support these uses cases ... no much effort is required, so stay tuned!

**Comment by mgrojo** [comment]
> For example, instead of an external file of variable definitions, you could directly provide a map from unbounded string to unbounded string to provide the required variable --> value mapping. If you want to work only in memory, wouldn't that be more appropriate?

Yes, this is what I had in mind, one parameter would be the input string, another the mapping of variable names to values. The result is returned (function) or assigned to an out parameter (procedure). Dumping the result to a file makes also sense. For my case, there will be no use for environment variables, as the values to use will be obtained from an `alire.toml` file by my program. If the user wants to generate the result file in a different way, they could also provide their own template.

I'm realizing that I could in fact use your library without any change, because I could always print the default template and request the library to do the substitutions with that :smile: But in any case, I think the proposal still makes sense for having a more generalized API. There would be cases where I/O wouldn't be wanted and yet, variable substitutions will still be very useful.

**Comment by rocher** [comment]
> I'm realizing that I could in fact use your library without any change, because I could always print the default template and request the library to do the substitutions

If the final result must be a file, then this is the best way: just print your template to `your-file.txt.mold` and apply the variable substitution with mold. Adjust the settings to remove the source file and the result will be in `your-file.txt`.

> the proposal still makes sense for having a more generalized API

Yes, and I realized that is quite immediate to implement it reusing the current design. There will be some missing features when working in memory:
 * variable substitution won't be applied to variable values (e.g. `A="Hello"`, `B="World"` and `C="{{A}}, {{B}}!"`, therefore `C="Hello, World!"`), to avoid modifying the variables mapping parameter.
 * template inclusion will be ignored: that would require reading a file in memory, appended to the original template string, and this is a mixed used case not considered for now (see below).

This is the function signature I have in mind:
```ada
   function Apply (
      Template  : String;
      Variables : not null Variables_Access;  --  Access to a Variables_Map object (hashed map)
      Settings  : Settings_Access := null;
      Filters   : Filters_Access  := null;
      Results   : Results_Access  := null;
      Log_Level : Log.Levels      := Log.Info
   ) return String;
```

I'm not considering mixed used cases in which, for example, you provide a template file and a hashed map with variables definitions; or vice-versa, you provide a template String and a toml file with variables definitions. For now, either you provide files or objects in memory.

BTW, do you have a link to your project?  With more context, I might help you more or provide additional insights.

**Comment by mgrojo** [comment]
Your proposal makes sense to me, and seems to fit my need perfectly.

> BTW, do you have a link to your project? With more context, I might help you more or provide additional insights.

For the moment, it's only an idea. You can understand it with [this issue](https://github.com/alire-project/alire/issues/1352) I opened in Alire and some internal notes I have (below). So basically I want to generate a `crate.desktop` taking information from an `alire.toml` and some predefined data. I'd also like to let the user provide their own template for the desktop file, by modifying the default template (meaning that I should print it and keep it, after all...).

It's probably going to take a long time, because I have some obligations filling my free time, but from time to time, I cannot resist procrastinating the obligations and thinking on the design of the idea.

# alr-appimage

`alr-appimage` is a tool to automatically create an AppImage executable from an Alire crate.

# How to use the tool

There are two prerequisites for your project to work with this tool:
- It has to be an Alire crate.
- It must be installable using `gprinstall`.

`alr-appimage` will use the following command for installing it:
 `alr exec -P -- gprinstall --prefix=$(DESTDIR) --create-missing-dirs --mode=usage -f`

Note: no longer needed if using Alire 2.0: `alr install`

If you simply run the tool inside an Alire crate, it will read the
metadata from your `alire.toml` file and create a default AppImage
from it.

The following metadata will be read from your `alire.toml` for the generation, and will be matched to the equivalent field of the `your_crate.desktop` file needed by the AppImage:
| Alire  | Desktop   | Comment  |
|---|---|---|
| `name` | `Name` |
| `description` | `Comment` |
| `tags` | `Keywords` | Additionally, any of the tags matching (case-insensitively) one of the main categories in the [freedesktop.org menu specification](https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html) will be used as `Categories`.
| `executables` | `Exec` |
| | `Terminal` | This field of the desktop entry will be set to `true`
| | `Type` | This field of the desktop entry will be set to `Application`

If these defaults are not good for your project, you can also define a template for your desktop file, and only the fields that you want will be included from the `alire.toml` or initialized by this utility.

**Comment by rocher** [comment]
> seems to fit my need perfectly

Yes, in this case working with files is the best alternative, I think.

`alr-appimage` is great idea, very interesting project!!
BTW, could alire itself be packaged as an AppImage with predefined toolchains (Linux, Windows, Apple)?  Makes sense?


Best regards,
-- Francesc
